name: Create data asset

on:
  push:
    branches:
     - 'main'
    paths:
    - 'src/model/*'
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops'
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops'
        type: string

env:
  rg: '****'
  amlw: '****'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Define rg and amlw
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "rg=${{ env.rg }}" >> "$GITHUB_ENV"
          echo "amlw=${{ env.amlw }}" >> "$GITHUB_ENV"
        else
          echo "rg=${{ github.event.inputs.resource_group }}" >> "$GITHUB_ENV"
          echo "amlw=${{ github.event.inputs.aml_workspace }}" >> "$GITHUB_ENV"
        fi

    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="${{ env.rg }}"
        az configure --defaults workspace="${{ env.amlw }}"

    - name: Create dataset in Azure ML workspace
      run: |
        cd experimentation
        az ml data create --name diabetes-folder --version 1 --path data